; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=gvn -S | FileCheck %s --check-prefixes=CHECK,MDEP
; RUN: opt < %s -passes='gvn<memoryssa>' -S | FileCheck %s --check-prefixes=CHECK,MSSA
; RUN: opt < %s -passes=gvn -enable-load-pre-diamond=false -S | FileCheck %s --check-prefix=NODIAMOND

; Load PRE candidates where the load is unavailable in several predecessors
; that form a transparent diamond, so that a single new load above the
; diamond's head would suffice.

declare void @clobber()
declare void @may_throw() memory(none)

; The value is available on the %avail edge into %head and unavailable on the
; %clobber edge. %merge sees it as unavailable in both %head and %then; %then
; only stores through a noalias pointer, so the load could be hoisted above %head
; with a new load in %clobber only.
define i32 @diamond_basic(ptr %p, ptr noalias %q, i1 %c1, i1 %c2) {
; CHECK-LABEL: define i32 @diamond_basic(
; CHECK-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    [[V_PRE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[V_PRE]], %[[CLOBBER]] ], [ 1, %[[AVAIL]] ]
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[Q]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_basic(
; NODIAMOND-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    store i32 2, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c1, label %avail, label %clobber

avail:
  store i32 1, ptr %p
  br label %head

clobber:
  call void @clobber()
  br label %head

head:
  br i1 %c2, label %then, label %merge

then:
  store i32 2, ptr %q
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; Both successors of the head are arms of the diamond.
define i32 @diamond_two_arms(ptr %p, ptr noalias %q, i1 %c1, i1 %c2) {
; CHECK-LABEL: define i32 @diamond_two_arms(
; CHECK-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    [[V_PRE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[V_PRE]], %[[CLOBBER]] ], [ 1, %[[AVAIL]] ]
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[Q]], align 4
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    store i32 3, ptr [[Q]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_two_arms(
; NODIAMOND-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[ELSE:.*]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    store i32 2, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE:.*]]
; NODIAMOND:       [[ELSE]]:
; NODIAMOND-NEXT:    store i32 3, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c1, label %avail, label %clobber

avail:
  store i32 1, ptr %p
  br label %head

clobber:
  call void @clobber()
  br label %head

head:
  br i1 %c2, label %then, label %else

then:
  store i32 2, ptr %q
  br label %merge

else:
  store i32 3, ptr %q
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; The head has a single-predecessor chain above it: a walk up from the head
; has to continue through %pre.head to insert the load in %clobber.
define i32 @diamond_chain_above_head(ptr %p, ptr noalias %q, i1 %c1, i1 %c2) {
; CHECK-LABEL: define i32 @diamond_chain_above_head(
; CHECK-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[PRE_HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    [[V_PRE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[PRE_HEAD]]
; CHECK:       [[PRE_HEAD]]:
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[V_PRE]], %[[CLOBBER]] ], [ 1, %[[AVAIL]] ]
; CHECK-NEXT:    store i32 4, ptr [[Q]], align 4
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[Q]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_chain_above_head(
; NODIAMOND-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[PRE_HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[PRE_HEAD]]
; NODIAMOND:       [[PRE_HEAD]]:
; NODIAMOND-NEXT:    store i32 4, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    store i32 2, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c1, label %avail, label %clobber

avail:
  store i32 1, ptr %p
  br label %pre.head

clobber:
  call void @clobber()
  br label %pre.head

pre.head:
  store i32 4, ptr %q
  br label %head

head:
  br i1 %c2, label %then, label %merge

then:
  store i32 2, ptr %q
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; The load sits below a single-predecessor chain under the diamond.
define i32 @diamond_chain_below_merge(ptr %p, ptr noalias %q, i1 %c1, i1 %c2) {
; CHECK-LABEL: define i32 @diamond_chain_below_merge(
; CHECK-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    [[V_PRE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[V_PRE]], %[[CLOBBER]] ], [ 1, %[[AVAIL]] ]
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[Q]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    store i32 5, ptr [[Q]], align 4
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_chain_below_merge(
; NODIAMOND-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    store i32 2, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    store i32 5, ptr [[Q]], align 4
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c1, label %avail, label %clobber

avail:
  store i32 1, ptr %p
  br label %head

clobber:
  call void @clobber()
  br label %head

head:
  br i1 %c2, label %then, label %merge

then:
  store i32 2, ptr %q
  br label %merge

merge:
  store i32 5, ptr %q
  br label %merge.cont

merge.cont:
  %v = load i32, ptr %p
  ret i32 %v
}

; Negative: the arm of the diamond may clobber the load.
define i32 @diamond_arm_clobbers(ptr %p, ptr %r, i1 %c1, i1 %c2) {
; CHECK-LABEL: define i32 @diamond_arm_clobbers(
; CHECK-SAME: ptr [[P:%.*]], ptr [[R:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[R]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_arm_clobbers(
; NODIAMOND-SAME: ptr [[P:%.*]], ptr [[R:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    store i32 2, ptr [[R]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c1, label %avail, label %clobber

avail:
  store i32 1, ptr %p
  br label %head

clobber:
  call void @clobber()
  br label %head

head:
  br i1 %c2, label %then, label %merge

then:
  store i32 2, ptr %r
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; Negative: the head has a successor that does not lead to the load, so hoisting
; above it would execute the load on a path where it was not executed before.
define i32 @diamond_head_exits(ptr %p, ptr noalias %q, i1 %c1, i32 %x) {
; CHECK-LABEL: define i32 @diamond_head_exits(
; CHECK-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    switch i32 [[X]], label %[[MERGE:.*]] [
; CHECK-NEXT:      i32 1, label %[[THEN:.*]]
; CHECK-NEXT:      i32 2, label %[[EXIT:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[Q]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_head_exits(
; NODIAMOND-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i32 [[X:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    switch i32 [[X]], label %[[MERGE:.*]] [
; NODIAMOND-NEXT:      i32 1, label %[[THEN:.*]]
; NODIAMOND-NEXT:      i32 2, label %[[EXIT:.*]]
; NODIAMOND-NEXT:    ]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    store i32 2, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[EXIT]]:
; NODIAMOND-NEXT:    ret i32 0
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c1, label %avail, label %clobber

avail:
  store i32 1, ptr %p
  br label %head

clobber:
  call void @clobber()
  br label %head

head:
  switch i32 %x, label %merge [
  i32 1, label %then
  i32 2, label %exit
  ]

then:
  store i32 2, ptr %q
  br label %merge

exit:
  ret i32 0

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; Negative: the arm has a second predecessor that bypasses the head.
define i32 @diamond_arm_extra_pred(ptr %p, ptr noalias %q, i1 %c1, i1 %c2, i1 %c3) {
; CHECK-LABEL: define i32 @diamond_arm_extra_pred(
; CHECK-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]], i1 [[C3:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C3]], label %[[BYPASS:.*]], label %[[SPLIT:.*]]
; CHECK:       [[SPLIT]]:
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[BYPASS]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    br label %[[THEN:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN]], label %[[MERGE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[Q]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_arm_extra_pred(
; NODIAMOND-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]], i1 [[C3:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C3]], label %[[BYPASS:.*]], label %[[SPLIT:.*]]
; NODIAMOND:       [[SPLIT]]:
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[BYPASS]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[THEN:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN]], label %[[MERGE:.*]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    store i32 2, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c3, label %bypass, label %split

split:
  br i1 %c1, label %avail, label %clobber

bypass:
  call void @clobber()
  br label %then

avail:
  store i32 1, ptr %p
  br label %head

clobber:
  call void @clobber()
  br label %head

head:
  br i1 %c2, label %then, label %merge

then:
  store i32 2, ptr %q
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; Negative: the address is a phi in the head, so it is not available in the
; head's predecessors and the diamond cannot be PHI-translated through.
define i32 @diamond_address_in_head(ptr %p1, ptr %p2, ptr noalias %q, i1 %c1, i1 %c2) {
; CHECK-LABEL: define i32 @diamond_address_in_head(
; CHECK-SAME: ptr [[P1:%.*]], ptr [[P2:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P1]], align 4
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    [[P:%.*]] = phi ptr [ [[P1]], %[[AVAIL]] ], [ [[P2]], %[[CLOBBER]] ]
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[Q]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_address_in_head(
; NODIAMOND-SAME: ptr [[P1:%.*]], ptr [[P2:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P1]], align 4
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    [[P:%.*]] = phi ptr [ [[P1]], %[[AVAIL]] ], [ [[P2]], %[[CLOBBER]] ]
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    store i32 2, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c1, label %avail, label %clobber

avail:
  store i32 1, ptr %p1
  br label %head

clobber:
  call void @clobber()
  br label %head

head:
  %p = phi ptr [ %p1, %avail ], [ %p2, %clobber ]
  br i1 %c2, label %then, label %merge

then:
  store i32 2, ptr %q
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; The arm contains a call that may not return: the hoisted load would execute
; where the original did not, which is only fine if the load is speculatable
; at the insertion point (second function: dereferenceable, aligned, and
; nothing on the way can free it).
define i32 @diamond_arm_icf(ptr %p, i1 %c1, i1 %c2) {
; CHECK-LABEL: define i32 @diamond_arm_icf(
; CHECK-SAME: ptr [[P:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    call void @may_throw()
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_arm_icf(
; NODIAMOND-SAME: ptr [[P:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    call void @may_throw()
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c1, label %avail, label %clobber

avail:
  store i32 1, ptr %p
  br label %head

clobber:
  call void @clobber()
  br label %head

head:
  br i1 %c2, label %then, label %merge

then:
  call void @may_throw()
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

define i32 @diamond_arm_icf_deref(ptr dereferenceable(4) align 4 %p, i1 %c1, i1 %c2) nofree {
; CHECK-LABEL: define i32 @diamond_arm_icf_deref(
; CHECK-SAME: ptr align 4 dereferenceable(4) [[P:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; CHECK:       [[AVAIL]]:
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    [[V_PRE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[V_PRE]], %[[CLOBBER]] ], [ 1, %[[AVAIL]] ]
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    call void @may_throw()
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_arm_icf_deref(
; NODIAMOND-SAME: ptr align 4 dereferenceable(4) [[P:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) #[[ATTR1:[0-9]+]] {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[AVAIL:.*]], label %[[CLOBBER:.*]]
; NODIAMOND:       [[AVAIL]]:
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE:.*]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    call void @may_throw()
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  br i1 %c1, label %avail, label %clobber

avail:
  store i32 1, ptr %p
  br label %head

clobber:
  call void @clobber()
  br label %head

head:
  br i1 %c2, label %then, label %merge

then:
  call void @may_throw()
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; Negative: the diamond closes a loop around the load's block; hoisting above
; its head would move the load across the backedge.
define i32 @diamond_backedge(ptr %p, ptr noalias %q, i1 %c1, i1 %c2, i1 %c3) {
; CHECK-LABEL: define i32 @diamond_backedge(
; CHECK-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]], i1 [[C3:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[S:%.*]] = add i32 [[V]], 1
; CHECK-NEXT:    store i32 [[S]], ptr [[Q]], align 4
; CHECK-NEXT:    br i1 [[C1]], label %[[BODY:.*]], label %[[EXIT:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    br i1 [[C3]], label %[[CLOBBER:.*]], label %[[HEAD:.*]]
; CHECK:       [[CLOBBER]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[Q]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[V]]
;
; NODIAMOND-LABEL: define i32 @diamond_backedge(
; NODIAMOND-SAME: ptr [[P:%.*]], ptr noalias [[Q:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]], i1 [[C3:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    store i32 1, ptr [[P]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE:.*]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; NODIAMOND-NEXT:    [[S:%.*]] = add i32 [[V]], 1
; NODIAMOND-NEXT:    store i32 [[S]], ptr [[Q]], align 4
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[BODY:.*]], label %[[EXIT:.*]]
; NODIAMOND:       [[BODY]]:
; NODIAMOND-NEXT:    br i1 [[C3]], label %[[CLOBBER:.*]], label %[[HEAD:.*]]
; NODIAMOND:       [[CLOBBER]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[THEN:.*]], label %[[MERGE]]
; NODIAMOND:       [[THEN]]:
; NODIAMOND-NEXT:    store i32 2, ptr [[Q]], align 4
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[EXIT]]:
; NODIAMOND-NEXT:    ret i32 [[V]]
;
entry:
  store i32 1, ptr %p
  br label %merge

merge:
  %v = load i32, ptr %p
  %s = add i32 %v, 1
  store i32 %s, ptr %q
  br i1 %c1, label %body, label %exit

body:
  br i1 %c3, label %clobber, label %head

clobber:
  call void @clobber()
  br label %head

head:
  br i1 %c2, label %then, label %merge

then:
  store i32 2, ptr %q
  br label %merge

exit:
  ret i32 %v
}

; The shape this was written for: two relaxed atomic accesses to a statistics
; counter of a different type between the store on one path and the reload on
; the merge; with TBAA they do not alias the i16 field.
define i16 @tcmalloc_shape(ptr %span, ptr %stats, i1 %c1, i1 %c2) {
; CHECK-LABEL: define i16 @tcmalloc_shape(
; CHECK-SAME: ptr [[SPAN:%.*]], ptr [[STATS:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ALLOCATED:%.*]] = getelementptr inbounds nuw i8, ptr [[SPAN]], i64 20
; CHECK-NEXT:    br i1 [[C1]], label %[[INLINE:.*]], label %[[OUTLINE:.*]]
; CHECK:       [[INLINE]]:
; CHECK-NEXT:    [[OLD:%.*]] = load i16, ptr [[ALLOCATED]], align 2, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[NEW:%.*]] = add i16 [[OLD]], 1
; CHECK-NEXT:    store i16 [[NEW]], ptr [[ALLOCATED]], align 2, !tbaa [[TBAA0]]
; CHECK-NEXT:    br label %[[HEAD:.*]]
; CHECK:       [[OUTLINE]]:
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    [[V_PRE:%.*]] = load i16, ptr [[ALLOCATED]], align 2, !tbaa [[TBAA0]]
; CHECK-NEXT:    br label %[[HEAD]]
; CHECK:       [[HEAD]]:
; CHECK-NEXT:    [[V:%.*]] = phi i16 [ [[V_PRE]], %[[OUTLINE]] ], [ [[NEW]], %[[INLINE]] ]
; CHECK-NEXT:    br i1 [[C2]], label %[[STAT:.*]], label %[[MERGE:.*]]
; CHECK:       [[STAT]]:
; CHECK-NEXT:    [[CNT:%.*]] = load atomic i64, ptr [[STATS]] monotonic, align 8, !tbaa [[TBAA5:![0-9]+]]
; CHECK-NEXT:    [[INC:%.*]] = add i64 [[CNT]], 1
; CHECK-NEXT:    store atomic i64 [[INC]], ptr [[STATS]] monotonic, align 8, !tbaa [[TBAA5]]
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    ret i16 [[V]]
;
; NODIAMOND-LABEL: define i16 @tcmalloc_shape(
; NODIAMOND-SAME: ptr [[SPAN:%.*]], ptr [[STATS:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; NODIAMOND-NEXT:  [[ENTRY:.*:]]
; NODIAMOND-NEXT:    [[ALLOCATED:%.*]] = getelementptr inbounds nuw i8, ptr [[SPAN]], i64 20
; NODIAMOND-NEXT:    br i1 [[C1]], label %[[INLINE:.*]], label %[[OUTLINE:.*]]
; NODIAMOND:       [[INLINE]]:
; NODIAMOND-NEXT:    [[OLD:%.*]] = load i16, ptr [[ALLOCATED]], align 2, !tbaa [[TBAA0:![0-9]+]]
; NODIAMOND-NEXT:    [[NEW:%.*]] = add i16 [[OLD]], 1
; NODIAMOND-NEXT:    store i16 [[NEW]], ptr [[ALLOCATED]], align 2, !tbaa [[TBAA0]]
; NODIAMOND-NEXT:    br label %[[HEAD:.*]]
; NODIAMOND:       [[OUTLINE]]:
; NODIAMOND-NEXT:    call void @clobber()
; NODIAMOND-NEXT:    br label %[[HEAD]]
; NODIAMOND:       [[HEAD]]:
; NODIAMOND-NEXT:    br i1 [[C2]], label %[[STAT:.*]], label %[[MERGE:.*]]
; NODIAMOND:       [[STAT]]:
; NODIAMOND-NEXT:    [[CNT:%.*]] = load atomic i64, ptr [[STATS]] monotonic, align 8, !tbaa [[TBAA5:![0-9]+]]
; NODIAMOND-NEXT:    [[INC:%.*]] = add i64 [[CNT]], 1
; NODIAMOND-NEXT:    store atomic i64 [[INC]], ptr [[STATS]] monotonic, align 8, !tbaa [[TBAA5]]
; NODIAMOND-NEXT:    br label %[[MERGE]]
; NODIAMOND:       [[MERGE]]:
; NODIAMOND-NEXT:    [[V:%.*]] = load i16, ptr [[ALLOCATED]], align 2, !tbaa [[TBAA0]]
; NODIAMOND-NEXT:    ret i16 [[V]]
;
entry:
  %allocated = getelementptr inbounds nuw i8, ptr %span, i64 20
  br i1 %c1, label %inline, label %outline

inline:
  %old = load i16, ptr %allocated, align 2, !tbaa !0
  %new = add i16 %old, 1
  store i16 %new, ptr %allocated, align 2, !tbaa !0
  br label %head

outline:
  call void @clobber()
  br label %head

head:
  br i1 %c2, label %stat, label %merge

stat:
  %cnt = load atomic i64, ptr %stats monotonic, align 8, !tbaa !5
  %inc = add i64 %cnt, 1
  store atomic i64 %inc, ptr %stats monotonic, align 8, !tbaa !5
  br label %merge

merge:
  %v = load i16, ptr %allocated, align 2, !tbaa !0
  ret i16 %v
}

!0 = !{!1, !2, i64 20}
!1 = !{!"Span", !2, i64 20}
!2 = !{!"short", !3, i64 0}
!3 = !{!"omnipotent char", !4, i64 0}
!4 = !{!"Simple C++ TBAA"}
!5 = !{!6, !7, i64 0}
!6 = !{!"AtomicCounter", !7, i64 0}
!7 = !{!"long", !3, i64 0}
;.
; CHECK: [[TBAA0]] = !{[[META1:![0-9]+]], [[META2:![0-9]+]], i64 20}
; CHECK: [[META1]] = !{!"Span", [[META2]], i64 20}
; CHECK: [[META2]] = !{!"short", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
; CHECK: [[META4]] = !{!"Simple C++ TBAA"}
; CHECK: [[TBAA5]] = !{[[META6:![0-9]+]], [[META7:![0-9]+]], i64 0}
; CHECK: [[META6]] = !{!"AtomicCounter", [[META7]], i64 0}
; CHECK: [[META7]] = !{!"long", [[META3]], i64 0}
;.
; NODIAMOND: [[TBAA0]] = !{[[META1:![0-9]+]], [[META2:![0-9]+]], i64 20}
; NODIAMOND: [[META1]] = !{!"Span", [[META2]], i64 20}
; NODIAMOND: [[META2]] = !{!"short", [[META3:![0-9]+]], i64 0}
; NODIAMOND: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
; NODIAMOND: [[META4]] = !{!"Simple C++ TBAA"}
; NODIAMOND: [[TBAA5]] = !{[[META6:![0-9]+]], [[META7:![0-9]+]], i64 0}
; NODIAMOND: [[META6]] = !{!"AtomicCounter", [[META7]], i64 0}
; NODIAMOND: [[META7]] = !{!"long", [[META3]], i64 0}
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; MDEP: {{.*}}
; MSSA: {{.*}}
