; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -enable-load-pre -enable-scalar-pre -passes=lcssa,gvn -S < %s | FileCheck %s
; Faithful reduction of protobuf RepeatedField<int>::Add inlined into a loop
; (fleetbench Message4_Set_2 shape). The header reloads size/capacity each
; iteration; the latch assumes equate the post-store reloads with registers.
; %f points into an ordinary heap object, so this is the case decided by
; performLoopLoadPRE's LoadPtr->canBeFreed() check.
define void @add_loop(ptr noundef nonnull align 8 dereferenceable(16) %f, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @add_loop(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[F:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[SZP:%.*]] = getelementptr inbounds i8, ptr [[F]], i64 8
; CHECK-NEXT:    [[CAPP:%.*]] = getelementptr inbounds i8, ptr [[F]], i64 12
; CHECK-NEXT:    [[WORD0:%.*]] = load i64, ptr [[F]], align 8
; CHECK-NEXT:    [[SZLOAD_PRE1:%.*]] = load i32, ptr [[SZP]], align 8
; CHECK-NEXT:    [[CAPLOAD_PRE4:%.*]] = load i32, ptr [[CAPP]], align 4
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[CAPLOAD:%.*]] = phi i32 [ [[CAPLOAD_PRE4]], %[[ENTRY]] ], [ [[CAPLOAD6:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[SZLOAD:%.*]] = phi i32 [ [[SZLOAD_PRE1]], %[[ENTRY]] ], [ [[SZLOAD3:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    [[WORD:%.*]] = phi i64 [ [[WORD0]], %[[ENTRY]] ], [ [[WORD_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    [[ELTP:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[IV]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[ELTP]], align 4
; CHECK-NEXT:    [[SOOBIT:%.*]] = and i64 [[WORD]], 4
; CHECK-NEXT:    [[IS_SOO:%.*]] = icmp eq i64 [[SOOBIT]], 0
; CHECK-NEXT:    [[WTRUNC:%.*]] = trunc i64 [[WORD]] to i32
; CHECK-NEXT:    [[SOOSZ:%.*]] = and i32 [[WTRUNC]], 3
; CHECK-NEXT:    [[SIZE:%.*]] = select i1 [[IS_SOO]], i32 [[SOOSZ]], i32 [[SZLOAD]]
; CHECK-NEXT:    [[CAP:%.*]] = select i1 [[IS_SOO]], i32 2, i32 [[CAPLOAD]]
; CHECK-NEXT:    [[HI:%.*]] = and i64 [[WORD]], -8
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i32 [[SIZE]], [[CAP]]
; CHECK-NEXT:    [[NEW_SIZE:%.*]] = add nsw i32 [[SIZE]], 1
; CHECK-NEXT:    br i1 [[FULL]], label %[[GROW:.*]], label %[[NOGROW:.*]], !prof [[PROF0:![0-9]+]]
; CHECK:       [[GROW]]:
; CHECK-NEXT:    call void @grow(ptr [[F]])
; CHECK-NEXT:    [[GWORD:%.*]] = load i64, ptr [[F]], align 8
; CHECK-NEXT:    [[GHI:%.*]] = and i64 [[GWORD]], -8
; CHECK-NEXT:    [[GSZ:%.*]] = load i32, ptr [[SZP]], align 8
; CHECK-NEXT:    br label %[[LONG:.*]]
; CHECK:       [[NOGROW]]:
; CHECK-NEXT:    br i1 [[IS_SOO]], label %[[SOO:.*]], label %[[LONG]]
; CHECK:       [[LONG]]:
; CHECK-NEXT:    [[LSZ:%.*]] = phi i32 [ [[GSZ]], %[[GROW]] ], [ [[SZLOAD]], %[[NOGROW]] ]
; CHECK-NEXT:    [[LHI:%.*]] = phi i64 [ [[GHI]], %[[GROW]] ], [ [[HI]], %[[NOGROW]] ]
; CHECK-NEXT:    [[BUF:%.*]] = inttoptr i64 [[LHI]] to ptr
; CHECK-NEXT:    store i32 [[NEW_SIZE]], ptr [[SZP]], align 8
; CHECK-NEXT:    [[IDX:%.*]] = sext i32 [[LSZ]] to i64
; CHECK-NEXT:    [[SLOT:%.*]] = getelementptr inbounds i32, ptr [[BUF]], i64 [[IDX]]
; CHECK-NEXT:    store i32 [[V]], ptr [[SLOT]], align 4
; CHECK-NEXT:    [[WORD_RL:%.*]] = load i64, ptr [[F]], align 8
; CHECK-NEXT:    [[SOOBIT_RL:%.*]] = and i64 [[WORD_RL]], 4
; CHECK-NEXT:    [[NOTSOO:%.*]] = icmp ne i64 [[SOOBIT_RL]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[NOTSOO]])
; CHECK-NEXT:    [[SZ_RL:%.*]] = load i32, ptr [[SZP]], align 8
; CHECK-NEXT:    [[EQSZ:%.*]] = icmp eq i32 [[NEW_SIZE]], [[SZ_RL]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[EQSZ]])
; CHECK-NEXT:    [[CAP_RL:%.*]] = load i32, ptr [[CAPP]], align 4
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[SOO]]:
; CHECK-NEXT:    [[LO:%.*]] = zext nneg i32 [[NEW_SIZE]] to i64
; CHECK-NEXT:    [[WORD_SOO:%.*]] = or disjoint i64 [[HI]], [[LO]]
; CHECK-NEXT:    store i64 [[WORD_SOO]], ptr [[F]], align 8
; CHECK-NEXT:    [[SOOIDX:%.*]] = and i64 [[WORD]], 3
; CHECK-NEXT:    [[SOOSLOT:%.*]] = getelementptr inbounds i32, ptr [[SZP]], i64 [[SOOIDX]]
; CHECK-NEXT:    store i32 [[V]], ptr [[SOOSLOT]], align 4
; CHECK-NEXT:    [[SZLOAD_PRE:%.*]] = load i32, ptr [[SZP]], align 8
; CHECK-NEXT:    [[CAPLOAD_PRE:%.*]] = load i32, ptr [[CAPP]], align 4
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[CAPLOAD6]] = phi i32 [ [[CAP_RL]], %[[LONG]] ], [ [[CAPLOAD_PRE]], %[[SOO]] ]
; CHECK-NEXT:    [[SZLOAD3]] = phi i32 [ [[NEW_SIZE]], %[[LONG]] ], [ [[SZLOAD_PRE]], %[[SOO]] ]
; CHECK-NEXT:    [[WORD_NEXT]] = phi i64 [ [[WORD_RL]], %[[LONG]] ], [ [[WORD_SOO]], %[[SOO]] ]
; CHECK-NEXT:    [[CAPA:%.*]] = phi i32 [ [[CAPLOAD]], %[[LONG]] ], [ 2, %[[SOO]] ]
; CHECK-NEXT:    [[CAPB:%.*]] = phi i32 [ [[CAP_RL]], %[[LONG]] ], [ 2, %[[SOO]] ]
; CHECK-NEXT:    [[EQCAP:%.*]] = icmp eq i32 [[CAPA]], [[CAPB]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[EQCAP]])
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i64 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %szp = getelementptr inbounds i8, ptr %f, i64 8
  %capp = getelementptr inbounds i8, ptr %f, i64 12
  %word0 = load i64, ptr %f, align 8
  br label %header

header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %word = phi i64 [ %word0, %entry ], [ %word.next, %latch ]
  %eltp = getelementptr inbounds i32, ptr %src, i64 %iv
  %v = load i32, ptr %eltp, align 4
  %soobit = and i64 %word, 4
  %is_soo = icmp eq i64 %soobit, 0
  %wtrunc = trunc i64 %word to i32
  %soosz = and i32 %wtrunc, 3
  %szload = load i32, ptr %szp, align 8        ; redundant along the long path
  %size = select i1 %is_soo, i32 %soosz, i32 %szload
  %capload = load i32, ptr %capp, align 4      ; redundant along the long path
  %cap = select i1 %is_soo, i32 2, i32 %capload
  %hi = and i64 %word, -8
  %full = icmp eq i32 %size, %cap
  %new_size = add nsw i32 %size, 1
  br i1 %full, label %grow, label %nogrow, !prof !0

grow:
  call void @grow(ptr %f)
  %gcap = load i32, ptr %capp, align 4
  %gword = load i64, ptr %f, align 8
  %ghi = and i64 %gword, -8
  %gsz = load i32, ptr %szp, align 8
  br label %long

nogrow:
  br i1 %is_soo, label %soo, label %long

long:
  %lsz = phi i32 [ %gsz, %grow ], [ %szload, %nogrow ]
  %lhi = phi i64 [ %ghi, %grow ], [ %hi, %nogrow ]
  %buf = inttoptr i64 %lhi to ptr
  store i32 %new_size, ptr %szp, align 8
  %idx = sext i32 %lsz to i64
  %slot = getelementptr inbounds i32, ptr %buf, i64 %idx
  store i32 %v, ptr %slot, align 4
  %word.rl = load i64, ptr %f, align 8
  %soobit.rl = and i64 %word.rl, 4
  %notsoo = icmp ne i64 %soobit.rl, 0
  call void @llvm.assume(i1 %notsoo)
  %sz.rl = load i32, ptr %szp, align 8
  %eqsz = icmp eq i32 %new_size, %sz.rl
  call void @llvm.assume(i1 %eqsz)
  %cap.rl = load i32, ptr %capp, align 4
  br label %latch

soo:
  %lo = zext nneg i32 %new_size to i64
  %word.soo = or disjoint i64 %hi, %lo
  store i64 %word.soo, ptr %f, align 8
  %sooidx = and i64 %word, 3
  %sooslot = getelementptr inbounds i32, ptr %szp, i64 %sooidx
  store i32 %v, ptr %sooslot, align 4          ; may alias szp/capp
  br label %latch

latch:
  %word.next = phi i64 [ %word.rl, %long ], [ %word.soo, %soo ]
  %capA = phi i32 [ %capload, %long ], [ 2, %soo ]
  %capB = phi i32 [ %cap.rl, %long ], [ 2, %soo ]
  %eqcap = icmp eq i32 %capA, %capB
  call void @llvm.assume(i1 %eqcap)
  %iv.next = add nuw i64 %iv, 1
  %done = icmp eq i64 %iv.next, %n
  br i1 %done, label %exit, label %header

exit:
  ret void
}
declare void @grow(ptr)
declare void @llvm.assume(i1)
!0 = !{!"branch_weights", i32 1, i32 2000}
;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 1, i32 2000}
;.
