; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; Tests the cases in which ICP must not evaluate its comparison before the CFI
; type test that guards the called value.

; RUN: opt < %s -passes=pgo-icall-prom -icp-total-percent-threshold=50 -S | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i32 @f1(i32 %x) !type !0 {
; CHECK-LABEL: define i32 @f1(
; CHECK-SAME: i32 [[X:%.*]]) !type [[META1:![0-9]+]] {
; CHECK-NEXT:    ret i32 [[X]]
;
  ret i32 %x
}

; @f2 does not carry the type, so it is not known to pass the type test.
define i32 @f2(i32 %x) {
; CHECK-LABEL: define i32 @f2(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    ret i32 [[X]]
;
  ret i32 %x
}

define i32 @D1_f(ptr %this, i32 %x) {
; CHECK-LABEL: define i32 @D1_f(
; CHECK-SAME: ptr [[THIS:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:    ret i32 [[X]]
;
  ret i32 %x
}

@D1_vtable = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @D1_f] }, !type !5

declare i1 @llvm.type.test(ptr, metadata)
declare void @llvm.ubsantrap(i8)
declare void @__cfi_slowpath(i64, ptr)
declare void @use(i32)
declare i32 @__gxx_personality_v0(...)

; The callee does not carry the type: the check stays in front of both calls.
define i32 @callee_without_type(ptr %fp, i32 %x) {
; CHECK-LABEL: define i32 @callee_without_type(
; CHECK-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; CHECK-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2:![0-9]+]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.ubsantrap(i8 2)
; CHECK-NEXT:    unreachable
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f2
; CHECK-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF3:![0-9]+]]
; CHECK:       [[IF_TRUE_DIRECT_TARG]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @f2(i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP:.*]]
; CHECK:       [[IF_FALSE_ORIG_INDIRECT]]:
; CHECK-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP]]
; CHECK:       [[IF_END_ICP]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; CHECK-NEXT:    ret i32 [[TMP2]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %fp, metadata !"_ZTSFiiE")
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  %r = call i32 %fp(i32 %x), !prof !3
  ret i32 %r
}

; A side effect before the call.
define i32 @side_effect_before_call(ptr %fp, i32 %x) {
; CHECK-LABEL: define i32 @side_effect_before_call(
; CHECK-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; CHECK-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.ubsantrap(i8 2)
; CHECK-NEXT:    unreachable
; CHECK:       [[CONT]]:
; CHECK-NEXT:    call void @use(i32 [[X]])
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; CHECK-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF3]]
; CHECK:       [[IF_TRUE_DIRECT_TARG]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP:.*]]
; CHECK:       [[IF_FALSE_ORIG_INDIRECT]]:
; CHECK-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP]]
; CHECK:       [[IF_END_ICP]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; CHECK-NEXT:    ret i32 [[TMP2]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %fp, metadata !"_ZTSFiiE")
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  call void @use(i32 %x)
  %r = call i32 %fp(i32 %x), !prof !1
  ret i32 %r
}

; A recoverable check (as with -fsanitize-cfi-cross-dso) continues to the call
; after the slow path, so the call's block has two predecessors.
define i32 @recoverable_check(ptr %fp, i32 %x) {
; CHECK-LABEL: define i32 @recoverable_check(
; CHECK-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; CHECK-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[SLOW:.*]], !prof [[PROF2]]
; CHECK:       [[SLOW]]:
; CHECK-NEXT:    call void @__cfi_slowpath(i64 1, ptr [[FP]])
; CHECK-NEXT:    br label %[[CONT]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; CHECK-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF3]]
; CHECK:       [[IF_TRUE_DIRECT_TARG]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP:.*]]
; CHECK:       [[IF_FALSE_ORIG_INDIRECT]]:
; CHECK-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP]]
; CHECK:       [[IF_END_ICP]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; CHECK-NEXT:    ret i32 [[TMP2]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %fp, metadata !"_ZTSFiiE")
  br i1 %t, label %cont, label %slow, !prof !2

slow:
  call void @__cfi_slowpath(i64 1, ptr %fp)
  br label %cont

cont:
  %r = call i32 %fp(i32 %x), !prof !1
  ret i32 %r
}

; The type test guards a different pointer.
define i32 @other_pointer(ptr %fp, ptr %other, i32 %x) {
; CHECK-LABEL: define i32 @other_pointer(
; CHECK-SAME: ptr [[FP:%.*]], ptr [[OTHER:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[OTHER]], metadata !"_ZTSFiiE")
; CHECK-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.ubsantrap(i8 2)
; CHECK-NEXT:    unreachable
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; CHECK-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF3]]
; CHECK:       [[IF_TRUE_DIRECT_TARG]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP:.*]]
; CHECK:       [[IF_FALSE_ORIG_INDIRECT]]:
; CHECK-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP]]
; CHECK:       [[IF_END_ICP]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; CHECK-NEXT:    ret i32 [[TMP2]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %other, metadata !"_ZTSFiiE")
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  %r = call i32 %fp(i32 %x), !prof !1
  ret i32 %r
}

; The type test guards the vtable pointer, but the comparison is against the
; function pointer loaded from it: the load must not be moved before the check.
define i32 @vcall_function_compare(ptr %obj, i32 %x) {
; CHECK-LABEL: define i32 @vcall_function_compare(
; CHECK-SAME: ptr [[OBJ:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[OBJ]], align 8
; CHECK-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"_ZTS4Base")
; CHECK-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.ubsantrap(i8 2)
; CHECK-NEXT:    unreachable
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 0
; CHECK-NEXT:    [[FN:%.*]] = load ptr, ptr [[VFN]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FN]], @D1_f
; CHECK-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF3]]
; CHECK:       [[IF_TRUE_DIRECT_TARG]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @D1_f(ptr [[OBJ]], i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP:.*]]
; CHECK:       [[IF_FALSE_ORIG_INDIRECT]]:
; CHECK-NEXT:    [[R:%.*]] = call i32 [[FN]](ptr [[OBJ]], i32 [[X]])
; CHECK-NEXT:    br label %[[IF_END_ICP]]
; CHECK:       [[IF_END_ICP]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; CHECK-NEXT:    ret i32 [[TMP2]]
;
entry:
  %vtable = load ptr, ptr %obj
  %t = call i1 @llvm.type.test(ptr %vtable, metadata !"_ZTS4Base")
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  %vfn = getelementptr inbounds ptr, ptr %vtable, i64 0
  %fn = load ptr, ptr %vfn
  %r = call i32 %fn(ptr %obj, i32 %x), !prof !4
  ret i32 %r
}

; Invokes are not handled.
define i32 @invoke_call(ptr %fp, i32 %x) personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: define i32 @invoke_call(
; CHECK-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) personality ptr @__gxx_personality_v0 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; CHECK-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.ubsantrap(i8 2)
; CHECK-NEXT:    unreachable
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; CHECK-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF3]]
; CHECK:       [[IF_TRUE_DIRECT_TARG]]:
; CHECK-NEXT:    [[TMP1:%.*]] = invoke i32 @f1(i32 [[X]])
; CHECK-NEXT:            to label %[[IF_END_ICP:.*]] unwind label %[[LPAD:.*]]
; CHECK:       [[IF_FALSE_ORIG_INDIRECT]]:
; CHECK-NEXT:    [[R:%.*]] = invoke i32 [[FP]](i32 [[X]])
; CHECK-NEXT:            to label %[[IF_END_ICP]] unwind label %[[LPAD]]
; CHECK:       [[IF_END_ICP]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; CHECK-NEXT:    br label %[[RET:.*]]
; CHECK:       [[RET]]:
; CHECK-NEXT:    ret i32 [[TMP2]]
; CHECK:       [[LPAD]]:
; CHECK-NEXT:    [[LP:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            cleanup
; CHECK-NEXT:    resume { ptr, i32 } [[LP]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %fp, metadata !"_ZTSFiiE")
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  %r = invoke i32 %fp(i32 %x)
  to label %ret unwind label %lpad, !prof !1

ret:
  ret i32 %r

lpad:
  %lp = landingpad { ptr, i32 }
  cleanup
  resume { ptr, i32 } %lp
}

!0 = !{i64 0, !"_ZTSFiiE"}
!1 = !{!"VP", i32 0, i64 1000, i64 2072045998141807037, i64 1000}
!2 = !{!"branch_weights", i32 1048575, i32 1}
!3 = !{!"VP", i32 0, i64 1000, i64 8471399308421654326, i64 1000}
!4 = !{!"VP", i32 0, i64 1000, i64 1753434612883758327, i64 1000}
!5 = !{i64 16, !"_ZTS4Base"}
;.
; CHECK: [[META1]] = !{i64 0, !"_ZTSFiiE"}
; CHECK: [[PROF2]] = !{!"branch_weights", i32 1048575, i32 1}
; CHECK: [[PROF3]] = !{!"branch_weights", i32 1000, i32 0}
;.
