; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; Tests that when the called value is guarded by a CFI type test that the
; promoted callee is known to pass, ICP evaluates its comparison before the
; type test, so that the direct call skips the check.

; RUN: opt < %s -passes=pgo-icall-prom -icp-total-percent-threshold=30 -S | FileCheck %s --check-prefixes=CHECK,HOIST
; RUN: opt < %s -passes=pgo-icall-prom -icp-total-percent-threshold=30 -icp-hoist-cond-above-type-test=false -S | FileCheck %s --check-prefixes=CHECK,NOHOIST

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i32 @f1(i32 %x) !type !0 {
; CHECK-LABEL: define i32 @f1(
; CHECK-SAME: i32 [[X:%.*]]) !type [[META0:![0-9]+]] {
; CHECK-NEXT:    ret i32 [[X]]
;
  ret i32 %x
}

define i32 @f3(i32 %x) !type !0 {
; CHECK-LABEL: define i32 @f3(
; CHECK-SAME: i32 [[X:%.*]]) !type [[META0]] {
; CHECK-NEXT:    ret i32 [[X]]
;
  ret i32 %x
}

declare i1 @llvm.type.test(ptr, metadata)
declare void @llvm.ubsantrap(i8)
declare void @llvm.pseudoprobe(i64, i64, i32, i64)

; The comparison is evaluated before the type test and the direct call is
; reached without it.
define i32 @guarded(ptr %fp, i32 %x) {
; HOIST-LABEL: define i32 @guarded(
; HOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; HOIST-NEXT:  [[ENTRY:.*:]]
; HOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; HOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_TYPE_TEST:.*]], !prof [[PROF1:![0-9]+]]
; HOIST:       [[IF_TYPE_TEST]]:
; HOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; HOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2:![0-9]+]]
; HOIST:       [[TRAP]]:
; HOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; HOIST-NEXT:    unreachable
; HOIST:       [[CONT]]:
; HOIST-NEXT:    br label %[[IF_FALSE_ORIG_INDIRECT:.*]]
; HOIST:       [[IF_TRUE_DIRECT_TARG]]:
; HOIST-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[X]])
; HOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; HOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; HOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[X]])
; HOIST-NEXT:    br label %[[IF_END_ICP]]
; HOIST:       [[IF_END_ICP]]:
; HOIST-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; HOIST-NEXT:    ret i32 [[TMP2]]
;
; NOHOIST-LABEL: define i32 @guarded(
; NOHOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; NOHOIST-NEXT:  [[ENTRY:.*:]]
; NOHOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; NOHOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF1:![0-9]+]]
; NOHOIST:       [[TRAP]]:
; NOHOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; NOHOIST-NEXT:    unreachable
; NOHOIST:       [[CONT]]:
; NOHOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; NOHOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF2:![0-9]+]]
; NOHOIST:       [[IF_TRUE_DIRECT_TARG]]:
; NOHOIST-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[X]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; NOHOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; NOHOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[X]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP]]
; NOHOIST:       [[IF_END_ICP]]:
; NOHOIST-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; NOHOIST-NEXT:    ret i32 [[TMP2]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %fp, metadata !"_ZTSFiiE")
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  %r = call i32 %fp(i32 %x), !prof !1
  ret i32 %r
}

; Instructions without side effects before the call are cloned onto the direct
; path, and their values get a phi node where they are used after the call.
define i32 @values_before_call(ptr %fp, i32 %x) {
; HOIST-LABEL: define i32 @values_before_call(
; HOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; HOIST-NEXT:  [[ENTRY:.*:]]
; HOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; HOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_TYPE_TEST:.*]], !prof [[PROF1]]
; HOIST:       [[IF_TYPE_TEST]]:
; HOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; HOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2]]
; HOIST:       [[TRAP]]:
; HOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; HOIST-NEXT:    unreachable
; HOIST:       [[CONT]]:
; HOIST-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; HOIST-NEXT:    br label %[[IF_FALSE_ORIG_INDIRECT:.*]]
; HOIST:       [[IF_TRUE_DIRECT_TARG]]:
; HOIST-NEXT:    [[Y1:%.*]] = add i32 [[X]], 1
; HOIST-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[Y1]])
; HOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; HOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; HOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[Y]])
; HOIST-NEXT:    br label %[[IF_END_ICP]]
; HOIST:       [[IF_END_ICP]]:
; HOIST-NEXT:    [[Y_ICP:%.*]] = phi i32 [ [[Y]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[Y1]], %[[IF_TRUE_DIRECT_TARG]] ]
; HOIST-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; HOIST-NEXT:    [[Z:%.*]] = add i32 [[TMP2]], [[Y_ICP]]
; HOIST-NEXT:    ret i32 [[Z]]
;
; NOHOIST-LABEL: define i32 @values_before_call(
; NOHOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; NOHOIST-NEXT:  [[ENTRY:.*:]]
; NOHOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; NOHOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF1]]
; NOHOIST:       [[TRAP]]:
; NOHOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; NOHOIST-NEXT:    unreachable
; NOHOIST:       [[CONT]]:
; NOHOIST-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; NOHOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; NOHOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF2]]
; NOHOIST:       [[IF_TRUE_DIRECT_TARG]]:
; NOHOIST-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[Y]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; NOHOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; NOHOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[Y]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP]]
; NOHOIST:       [[IF_END_ICP]]:
; NOHOIST-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; NOHOIST-NEXT:    [[Z:%.*]] = add i32 [[TMP2]], [[Y]]
; NOHOIST-NEXT:    ret i32 [[Z]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %fp, metadata !"_ZTSFiiE")
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  %y = add i32 %x, 1
  %r = call i32 %fp(i32 %y), !prof !1
  %z = add i32 %r, %y
  ret i32 %z
}

; A pseudo probe stays with the indirect call.
define i32 @pseudo_probe(ptr %fp, i32 %x) {
; HOIST-LABEL: define i32 @pseudo_probe(
; HOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; HOIST-NEXT:  [[ENTRY:.*:]]
; HOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; HOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_TYPE_TEST:.*]], !prof [[PROF1]]
; HOIST:       [[IF_TYPE_TEST]]:
; HOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; HOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2]]
; HOIST:       [[TRAP]]:
; HOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; HOIST-NEXT:    unreachable
; HOIST:       [[CONT]]:
; HOIST-NEXT:    call void @llvm.pseudoprobe(i64 1, i64 2, i32 0, i64 -1)
; HOIST-NEXT:    br label %[[IF_FALSE_ORIG_INDIRECT:.*]]
; HOIST:       [[IF_TRUE_DIRECT_TARG]]:
; HOIST-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[X]])
; HOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; HOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; HOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[X]])
; HOIST-NEXT:    br label %[[IF_END_ICP]]
; HOIST:       [[IF_END_ICP]]:
; HOIST-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; HOIST-NEXT:    ret i32 [[TMP2]]
;
; NOHOIST-LABEL: define i32 @pseudo_probe(
; NOHOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; NOHOIST-NEXT:  [[ENTRY:.*:]]
; NOHOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; NOHOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF1]]
; NOHOIST:       [[TRAP]]:
; NOHOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; NOHOIST-NEXT:    unreachable
; NOHOIST:       [[CONT]]:
; NOHOIST-NEXT:    call void @llvm.pseudoprobe(i64 1, i64 2, i32 0, i64 -1)
; NOHOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; NOHOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF2]]
; NOHOIST:       [[IF_TRUE_DIRECT_TARG]]:
; NOHOIST-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[X]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; NOHOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; NOHOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[X]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP]]
; NOHOIST:       [[IF_END_ICP]]:
; NOHOIST-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; NOHOIST-NEXT:    ret i32 [[TMP2]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %fp, metadata !"_ZTSFiiE")
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  call void @llvm.pseudoprobe(i64 1, i64 2, i32 0, i64 -1)
  %r = call i32 %fp(i32 %x), !prof !1
  ret i32 %r
}

; The type test is not right before the branch: only the branch is moved
; behind the comparison.
define i32 @test_not_before_branch(ptr %fp, i32 %x) {
; HOIST-LABEL: define i32 @test_not_before_branch(
; HOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; HOIST-NEXT:  [[ENTRY:.*:]]
; HOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; HOIST-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; HOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; HOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_TYPE_TEST:.*]], !prof [[PROF1]]
; HOIST:       [[IF_TYPE_TEST]]:
; HOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2]]
; HOIST:       [[TRAP]]:
; HOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; HOIST-NEXT:    unreachable
; HOIST:       [[CONT]]:
; HOIST-NEXT:    br label %[[IF_FALSE_ORIG_INDIRECT:.*]]
; HOIST:       [[IF_TRUE_DIRECT_TARG]]:
; HOIST-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[Y]])
; HOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; HOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; HOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[Y]])
; HOIST-NEXT:    br label %[[IF_END_ICP]]
; HOIST:       [[IF_END_ICP]]:
; HOIST-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; HOIST-NEXT:    ret i32 [[TMP2]]
;
; NOHOIST-LABEL: define i32 @test_not_before_branch(
; NOHOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; NOHOIST-NEXT:  [[ENTRY:.*:]]
; NOHOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; NOHOIST-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; NOHOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF1]]
; NOHOIST:       [[TRAP]]:
; NOHOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; NOHOIST-NEXT:    unreachable
; NOHOIST:       [[CONT]]:
; NOHOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; NOHOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF2]]
; NOHOIST:       [[IF_TRUE_DIRECT_TARG]]:
; NOHOIST-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[Y]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; NOHOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; NOHOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[Y]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP]]
; NOHOIST:       [[IF_END_ICP]]:
; NOHOIST-NEXT:    [[TMP2:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; NOHOIST-NEXT:    ret i32 [[TMP2]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %fp, metadata !"_ZTSFiiE")
  %y = add i32 %x, 1
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  %r = call i32 %fp(i32 %y), !prof !1
  ret i32 %r
}

; Every promoted candidate is compared before the type test, also when the
; call site was already promoted to another candidate.
define i32 @two_candidates(ptr %fp, i32 %x) {
; HOIST-LABEL: define i32 @two_candidates(
; HOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; HOIST-NEXT:  [[ENTRY:.*:]]
; HOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; HOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_TYPE_TEST:.*]], !prof [[PROF3:![0-9]+]]
; HOIST:       [[IF_TYPE_TEST]]:
; HOIST-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[FP]], @f3
; HOIST-NEXT:    br i1 [[TMP1]], label %[[IF_TRUE_DIRECT_TARG2:.*]], label %[[IF_TYPE_TEST5:.*]], !prof [[PROF4:![0-9]+]]
; HOIST:       [[IF_TYPE_TEST5]]:
; HOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; HOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF2]]
; HOIST:       [[TRAP]]:
; HOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; HOIST-NEXT:    unreachable
; HOIST:       [[CONT]]:
; HOIST-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; HOIST-NEXT:    br label %[[IF_FALSE_ORIG_INDIRECT:.*]]
; HOIST:       [[IF_TRUE_DIRECT_TARG]]:
; HOIST-NEXT:    [[Y1:%.*]] = add i32 [[X]], 1
; HOIST-NEXT:    [[TMP2:%.*]] = call i32 @f1(i32 [[Y1]])
; HOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; HOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; HOIST-NEXT:    br label %[[IF_FALSE_ORIG_INDIRECT3:.*]]
; HOIST:       [[IF_TRUE_DIRECT_TARG2]]:
; HOIST-NEXT:    [[Y6:%.*]] = add i32 [[X]], 1
; HOIST-NEXT:    [[TMP3:%.*]] = call i32 @f3(i32 [[Y6]])
; HOIST-NEXT:    br label %[[IF_END_ICP4:.*]]
; HOIST:       [[IF_FALSE_ORIG_INDIRECT3]]:
; HOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[Y]])
; HOIST-NEXT:    br label %[[IF_END_ICP4]]
; HOIST:       [[IF_END_ICP4]]:
; HOIST-NEXT:    [[Y_ICP7:%.*]] = phi i32 [ [[Y]], %[[IF_FALSE_ORIG_INDIRECT3]] ], [ [[Y6]], %[[IF_TRUE_DIRECT_TARG2]] ]
; HOIST-NEXT:    [[TMP4:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT3]] ], [ [[TMP3]], %[[IF_TRUE_DIRECT_TARG2]] ]
; HOIST-NEXT:    br label %[[IF_END_ICP]]
; HOIST:       [[IF_END_ICP]]:
; HOIST-NEXT:    [[Y_ICP:%.*]] = phi i32 [ [[Y_ICP7]], %[[IF_END_ICP4]] ], [ [[Y1]], %[[IF_TRUE_DIRECT_TARG]] ]
; HOIST-NEXT:    [[TMP5:%.*]] = phi i32 [ [[TMP4]], %[[IF_END_ICP4]] ], [ [[TMP2]], %[[IF_TRUE_DIRECT_TARG]] ]
; HOIST-NEXT:    [[Z:%.*]] = add i32 [[TMP5]], [[Y_ICP]]
; HOIST-NEXT:    ret i32 [[Z]]
;
; NOHOIST-LABEL: define i32 @two_candidates(
; NOHOIST-SAME: ptr [[FP:%.*]], i32 [[X:%.*]]) {
; NOHOIST-NEXT:  [[ENTRY:.*:]]
; NOHOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[FP]], metadata !"_ZTSFiiE")
; NOHOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF1]]
; NOHOIST:       [[TRAP]]:
; NOHOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; NOHOIST-NEXT:    unreachable
; NOHOIST:       [[CONT]]:
; NOHOIST-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; NOHOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[FP]], @f1
; NOHOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF3:![0-9]+]]
; NOHOIST:       [[IF_TRUE_DIRECT_TARG]]:
; NOHOIST-NEXT:    [[TMP1:%.*]] = call i32 @f1(i32 [[Y]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; NOHOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; NOHOIST-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[FP]], @f3
; NOHOIST-NEXT:    br i1 [[TMP2]], label %[[IF_TRUE_DIRECT_TARG1:.*]], label %[[IF_FALSE_ORIG_INDIRECT2:.*]], !prof [[PROF4:![0-9]+]]
; NOHOIST:       [[IF_TRUE_DIRECT_TARG1]]:
; NOHOIST-NEXT:    [[TMP3:%.*]] = call i32 @f3(i32 [[Y]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP3:.*]]
; NOHOIST:       [[IF_FALSE_ORIG_INDIRECT2]]:
; NOHOIST-NEXT:    [[R:%.*]] = call i32 [[FP]](i32 [[Y]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP3]]
; NOHOIST:       [[IF_END_ICP3]]:
; NOHOIST-NEXT:    [[TMP4:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT2]] ], [ [[TMP3]], %[[IF_TRUE_DIRECT_TARG1]] ]
; NOHOIST-NEXT:    br label %[[IF_END_ICP]]
; NOHOIST:       [[IF_END_ICP]]:
; NOHOIST-NEXT:    [[TMP5:%.*]] = phi i32 [ [[TMP4]], %[[IF_END_ICP3]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; NOHOIST-NEXT:    [[Z:%.*]] = add i32 [[TMP5]], [[Y]]
; NOHOIST-NEXT:    ret i32 [[Z]]
;
entry:
  %t = call i1 @llvm.type.test(ptr %fp, metadata !"_ZTSFiiE")
  br i1 %t, label %cont, label %trap, !prof !2

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  %y = add i32 %x, 1
  %r = call i32 %fp(i32 %y), !prof !3
  %z = add i32 %r, %y
  ret i32 %z
}

!0 = !{i64 0, !"_ZTSFiiE"}
!1 = !{!"VP", i32 0, i64 1000, i64 2072045998141807037, i64 1000}
!2 = !{!"branch_weights", i32 1048575, i32 1}
!3 = !{!"VP", i32 0, i64 1000, i64 2072045998141807037, i64 600, i64 4197650231481825559, i64 400}
;.
; HOIST: [[META0]] = !{i64 0, !"_ZTSFiiE"}
; HOIST: [[PROF1]] = !{!"branch_weights", i32 1000, i32 0}
; HOIST: [[PROF2]] = !{!"branch_weights", i32 1048575, i32 1}
; HOIST: [[PROF3]] = !{!"branch_weights", i32 600, i32 400}
; HOIST: [[PROF4]] = !{!"branch_weights", i32 400, i32 0}
;.
; NOHOIST: [[META0]] = !{i64 0, !"_ZTSFiiE"}
; NOHOIST: [[PROF1]] = !{!"branch_weights", i32 1048575, i32 1}
; NOHOIST: [[PROF2]] = !{!"branch_weights", i32 1000, i32 0}
; NOHOIST: [[PROF3]] = !{!"branch_weights", i32 600, i32 400}
; NOHOIST: [[PROF4]] = !{!"branch_weights", i32 400, i32 0}
;.
