; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; Tests that a virtual call guarded by a -fsanitize=cfi-vcall type test on the
; vtable pointer is promoted based on vtable profiles, and that the vtable
; comparison is evaluated before the type test, so that the direct call skips
; both the check and the load of the function pointer.

; RUN: opt < %s -passes=pgo-icall-prom -enable-vtable-profile-use -icp-max-num-vtable-last-candidate=2 -pass-remarks=pgo-icall-prom -S 2>&1 | FileCheck %s --check-prefixes=CHECK,HOIST
; RUN: opt < %s -passes=pgo-icall-prom -enable-vtable-profile-use -icp-max-num-vtable-last-candidate=2 -icp-hoist-cond-above-type-test=false -S | FileCheck %s --check-prefixes=CHECK,NOHOIST

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@Base = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @Base_foo] }, !type !0
@Derived1 = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @Derived1_foo] }, !type !0, !type !1
@Derived2 = constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @Derived2_foo] }, !type !0, !type !2

; HOIST: remark: <unknown>:0:0: Promote indirect call to Derived1_foo with count 600 out of 1000, sink 2 instruction(s) and compare 1 vtable(s): {Derived1}
; HOIST: remark: <unknown>:0:0: Promote indirect call to Derived2_foo with count 400 out of 400, sink 2 instruction(s) and compare 1 vtable(s): {Derived2}

define i32 @test(ptr %d, i32 %x) {
; HOIST-LABEL: define i32 @test(
; HOIST-SAME: ptr [[D:%.*]], i32 [[X:%.*]]) {
; HOIST-NEXT:  [[ENTRY:.*:]]
; HOIST-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[D]], align 8
; HOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[VTABLE]], getelementptr inbounds (i8, ptr @Derived1, i32 16)
; HOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_TYPE_TEST:.*]], !prof [[PROF3:![0-9]+]]
; HOIST:       [[IF_TYPE_TEST]]:
; HOIST-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[VTABLE]], getelementptr inbounds (i8, ptr @Derived2, i32 16)
; HOIST-NEXT:    br i1 [[TMP1]], label %[[IF_TRUE_DIRECT_TARG3:.*]], label %[[IF_TYPE_TEST6:.*]], !prof [[PROF4:![0-9]+]]
; HOIST:       [[IF_TYPE_TEST6]]:
; HOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"Base")
; HOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF5:![0-9]+]]
; HOIST:       [[TRAP]]:
; HOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; HOIST-NEXT:    unreachable
; HOIST:       [[CONT]]:
; HOIST-NEXT:    br label %[[IF_FALSE_ORIG_INDIRECT:.*]]
; HOIST:       [[IF_TRUE_DIRECT_TARG]]:
; HOIST-NEXT:    [[TMP2:%.*]] = call i32 @Derived1_foo(ptr [[D]], i32 [[X]])
; HOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; HOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; HOIST-NEXT:    br label %[[IF_FALSE_ORIG_INDIRECT4:.*]]
; HOIST:       [[IF_TRUE_DIRECT_TARG3]]:
; HOIST-NEXT:    [[TMP3:%.*]] = call i32 @Derived2_foo(ptr [[D]], i32 [[X]])
; HOIST-NEXT:    br label %[[IF_END_ICP5:.*]]
; HOIST:       [[IF_FALSE_ORIG_INDIRECT4]]:
; HOIST-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 0
; HOIST-NEXT:    [[FN:%.*]] = load ptr, ptr [[VFN]], align 8
; HOIST-NEXT:    [[R:%.*]] = call i32 [[FN]](ptr [[D]], i32 [[X]])
; HOIST-NEXT:    br label %[[IF_END_ICP5]]
; HOIST:       [[IF_END_ICP5]]:
; HOIST-NEXT:    [[TMP4:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT4]] ], [ [[TMP3]], %[[IF_TRUE_DIRECT_TARG3]] ]
; HOIST-NEXT:    br label %[[IF_END_ICP]]
; HOIST:       [[IF_END_ICP]]:
; HOIST-NEXT:    [[TMP5:%.*]] = phi i32 [ [[TMP4]], %[[IF_END_ICP5]] ], [ [[TMP2]], %[[IF_TRUE_DIRECT_TARG]] ]
; HOIST-NEXT:    ret i32 [[TMP5]]
;
; NOHOIST-LABEL: define i32 @test(
; NOHOIST-SAME: ptr [[D:%.*]], i32 [[X:%.*]]) {
; NOHOIST-NEXT:  [[ENTRY:.*:]]
; NOHOIST-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[D]], align 8
; NOHOIST-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"Base")
; NOHOIST-NEXT:    br i1 [[T]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF3:![0-9]+]]
; NOHOIST:       [[TRAP]]:
; NOHOIST-NEXT:    call void @llvm.ubsantrap(i8 2)
; NOHOIST-NEXT:    unreachable
; NOHOIST:       [[CONT]]:
; NOHOIST-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[VTABLE]], getelementptr inbounds (i8, ptr @Derived1, i32 16)
; NOHOIST-NEXT:    br i1 [[TMP0]], label %[[IF_TRUE_DIRECT_TARG:.*]], label %[[IF_FALSE_ORIG_INDIRECT:.*]], !prof [[PROF4:![0-9]+]]
; NOHOIST:       [[IF_TRUE_DIRECT_TARG]]:
; NOHOIST-NEXT:    [[TMP1:%.*]] = call i32 @Derived1_foo(ptr [[D]], i32 [[X]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP:.*]]
; NOHOIST:       [[IF_FALSE_ORIG_INDIRECT]]:
; NOHOIST-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[VTABLE]], getelementptr inbounds (i8, ptr @Derived2, i32 16)
; NOHOIST-NEXT:    br i1 [[TMP2]], label %[[IF_TRUE_DIRECT_TARG1:.*]], label %[[IF_FALSE_ORIG_INDIRECT2:.*]], !prof [[PROF5:![0-9]+]]
; NOHOIST:       [[IF_TRUE_DIRECT_TARG1]]:
; NOHOIST-NEXT:    [[TMP3:%.*]] = call i32 @Derived2_foo(ptr [[D]], i32 [[X]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP3:.*]]
; NOHOIST:       [[IF_FALSE_ORIG_INDIRECT2]]:
; NOHOIST-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 0
; NOHOIST-NEXT:    [[FN:%.*]] = load ptr, ptr [[VFN]], align 8
; NOHOIST-NEXT:    [[R:%.*]] = call i32 [[FN]](ptr [[D]], i32 [[X]])
; NOHOIST-NEXT:    br label %[[IF_END_ICP3]]
; NOHOIST:       [[IF_END_ICP3]]:
; NOHOIST-NEXT:    [[TMP4:%.*]] = phi i32 [ [[R]], %[[IF_FALSE_ORIG_INDIRECT2]] ], [ [[TMP3]], %[[IF_TRUE_DIRECT_TARG1]] ]
; NOHOIST-NEXT:    br label %[[IF_END_ICP]]
; NOHOIST:       [[IF_END_ICP]]:
; NOHOIST-NEXT:    [[TMP5:%.*]] = phi i32 [ [[TMP4]], %[[IF_END_ICP3]] ], [ [[TMP1]], %[[IF_TRUE_DIRECT_TARG]] ]
; NOHOIST-NEXT:    ret i32 [[TMP5]]
;
entry:
  %vtable = load ptr, ptr %d, !prof !3
  %t = call i1 @llvm.type.test(ptr %vtable, metadata !"Base")
  br i1 %t, label %cont, label %trap, !prof !5

trap:
  call void @llvm.ubsantrap(i8 2)
  unreachable

cont:
  %vfn = getelementptr inbounds ptr, ptr %vtable, i64 0
  %fn = load ptr, ptr %vfn
  %r = call i32 %fn(ptr %d, i32 %x), !prof !4
  ret i32 %r
}

define i32 @Base_foo(ptr %this, i32 %x) {
; CHECK-LABEL: define i32 @Base_foo(
; CHECK-SAME: ptr [[THIS:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:    ret i32 [[X]]
;
  ret i32 %x
}

define i32 @Derived1_foo(ptr %this, i32 %x) {
; CHECK-LABEL: define i32 @Derived1_foo(
; CHECK-SAME: ptr [[THIS:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:    ret i32 [[X]]
;
  ret i32 %x
}

define i32 @Derived2_foo(ptr %this, i32 %x) {
; CHECK-LABEL: define i32 @Derived2_foo(
; CHECK-SAME: ptr [[THIS:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:    ret i32 [[X]]
;
  ret i32 %x
}

declare i1 @llvm.type.test(ptr, metadata)
declare void @llvm.ubsantrap(i8)

!0 = !{i64 16, !"Base"}
!1 = !{i64 16, !"Derived1"}
!2 = !{i64 16, !"Derived2"}
!3 = !{!"VP", i32 2, i64 1000, i64 -4123858694673519054, i64 600, i64 -7211198353767973908, i64 400}
!4 = !{!"VP", i32 0, i64 1000, i64 -4986521108747669053, i64 600, i64 -827740165941323480, i64 400}
!5 = !{!"branch_weights", i32 1048575, i32 1}
;.
; HOIST: [[PROF3]] = !{!"branch_weights", i32 600, i32 400}
; HOIST: [[PROF4]] = !{!"branch_weights", i32 400, i32 0}
; HOIST: [[PROF5]] = !{!"branch_weights", i32 1048575, i32 1}
;.
; NOHOIST: [[PROF3]] = !{!"branch_weights", i32 1048575, i32 1}
; NOHOIST: [[PROF4]] = !{!"branch_weights", i32 600, i32 400}
; NOHOIST: [[PROF5]] = !{!"branch_weights", i32 400, i32 0}
;.
