; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu -relocation-model=pic < %s | FileCheck %s --check-prefix=GENERIC
; RUN: llc -mtriple=aarch64-linux-gnu -relocation-model=pic -mcpu=neoverse-v2 < %s | FileCheck %s --check-prefix=V2
; RUN: llc -mtriple=aarch64-linux-gnu_ilp32 -relocation-model=pic -mcpu=neoverse-v2 < %s | FileCheck %s --check-prefix=ILP32
; RUN: llc -mtriple=aarch64-linux-gnu -relocation-model=pic -mcpu=cortex-a55 < %s | FileCheck %s --check-prefix=A55

; A linker may only relax an ADRP of a GOT page and the LDR of the GOT entry
; when the two instructions are adjacent (and LLD relaxes none of a symbol's
; pairs in a section unless all of them are).

@g1 = external global i64
@g2 = external global i64
@g3 = external global i64
@g4 = external global i64

define i64 @load4() {
; GENERIC-LABEL: load4:
; GENERIC:       // %bb.0:
; GENERIC-NEXT:    adrp x8, :got:g1
; GENERIC-NEXT:    adrp x9, :got:g2
; GENERIC-NEXT:    adrp x10, :got:g3
; GENERIC-NEXT:    adrp x11, :got:g4
; GENERIC-NEXT:    ldr x8, [x8, :got_lo12:g1]
; GENERIC-NEXT:    ldr x9, [x9, :got_lo12:g2]
; GENERIC-NEXT:    ldr x10, [x10, :got_lo12:g3]
; GENERIC-NEXT:    ldr x11, [x11, :got_lo12:g4]
; GENERIC-NEXT:    ldr x8, [x8]
; GENERIC-NEXT:    ldr x9, [x9]
; GENERIC-NEXT:    ldr x10, [x10]
; GENERIC-NEXT:    ldr x11, [x11]
; GENERIC-NEXT:    add x8, x9, x8
; GENERIC-NEXT:    add x9, x10, x11
; GENERIC-NEXT:    add x0, x8, x9
; GENERIC-NEXT:    ret
;
; V2-LABEL: load4:
; V2:       // %bb.0:
; V2-NEXT:    adrp x8, :got:g1
; V2-NEXT:    adrp x9, :got:g2
; V2-NEXT:    adrp x10, :got:g4
; V2-NEXT:    ldr x8, [x8, :got_lo12:g1]
; V2-NEXT:    ldr x8, [x8]
; V2-NEXT:    ldr x9, [x9, :got_lo12:g2]
; V2-NEXT:    ldr x9, [x9]
; V2-NEXT:    add x8, x9, x8
; V2-NEXT:    adrp x9, :got:g3
; V2-NEXT:    ldr x9, [x9, :got_lo12:g3]
; V2-NEXT:    ldr x9, [x9]
; V2-NEXT:    ldr x10, [x10, :got_lo12:g4]
; V2-NEXT:    ldr x10, [x10]
; V2-NEXT:    add x9, x9, x10
; V2-NEXT:    add x0, x8, x9
; V2-NEXT:    ret
;
; ILP32-LABEL: load4:
; ILP32:       // %bb.0:
; ILP32-NEXT:    adrp x8, :got:g1
; ILP32-NEXT:    adrp x9, :got:g2
; ILP32-NEXT:    adrp x10, :got:g4
; ILP32-NEXT:    ldr w8, [x8, :got_lo12:g1]
; ILP32-NEXT:    ldr x8, [x8]
; ILP32-NEXT:    ldr w9, [x9, :got_lo12:g2]
; ILP32-NEXT:    ldr x9, [x9]
; ILP32-NEXT:    add x8, x9, x8
; ILP32-NEXT:    adrp x9, :got:g3
; ILP32-NEXT:    ldr w9, [x9, :got_lo12:g3]
; ILP32-NEXT:    ldr x9, [x9]
; ILP32-NEXT:    ldr w10, [x10, :got_lo12:g4]
; ILP32-NEXT:    ldr x10, [x10]
; ILP32-NEXT:    add x9, x9, x10
; ILP32-NEXT:    add x0, x8, x9
; ILP32-NEXT:    ret
;
; A55-LABEL: load4:
; A55:       // %bb.0:
; A55-NEXT:    adrp x8, :got:g1
; A55-NEXT:    ldr x8, [x8, :got_lo12:g1]
; A55-NEXT:    adrp x9, :got:g2
; A55-NEXT:    ldr x9, [x9, :got_lo12:g2]
; A55-NEXT:    adrp x10, :got:g3
; A55-NEXT:    ldr x10, [x10, :got_lo12:g3]
; A55-NEXT:    ldr x8, [x8]
; A55-NEXT:    adrp x11, :got:g4
; A55-NEXT:    ldr x11, [x11, :got_lo12:g4]
; A55-NEXT:    ldr x9, [x9]
; A55-NEXT:    ldr x10, [x10]
; A55-NEXT:    ldr x11, [x11]
; A55-NEXT:    add x8, x9, x8
; A55-NEXT:    add x9, x10, x11
; A55-NEXT:    add x0, x8, x9
; A55-NEXT:    ret
  %1 = load i64, ptr @g1
  %2 = load i64, ptr @g2
  %3 = add i64 %2, %1
  %4 = load i64, ptr @g3
  %5 = add i64 %3, %4
  %6 = load i64, ptr @g4
  %7 = add i64 %5, %6
  ret i64 %7
}

define void @store4(i64 %x) {
; GENERIC-LABEL: store4:
; GENERIC:       // %bb.0:
; GENERIC-NEXT:    adrp x8, :got:g1
; GENERIC-NEXT:    adrp x9, :got:g2
; GENERIC-NEXT:    adrp x10, :got:g3
; GENERIC-NEXT:    ldr x8, [x8, :got_lo12:g1]
; GENERIC-NEXT:    ldr x9, [x9, :got_lo12:g2]
; GENERIC-NEXT:    ldr x10, [x10, :got_lo12:g3]
; GENERIC-NEXT:    str x0, [x8]
; GENERIC-NEXT:    adrp x8, :got:g4
; GENERIC-NEXT:    str x0, [x9]
; GENERIC-NEXT:    ldr x8, [x8, :got_lo12:g4]
; GENERIC-NEXT:    str x0, [x10]
; GENERIC-NEXT:    str x0, [x8]
; GENERIC-NEXT:    ret
;
; V2-LABEL: store4:
; V2:       // %bb.0:
; V2-NEXT:    adrp x8, :got:g1
; V2-NEXT:    ldr x8, [x8, :got_lo12:g1]
; V2-NEXT:    str x0, [x8]
; V2-NEXT:    adrp x8, :got:g2
; V2-NEXT:    ldr x8, [x8, :got_lo12:g2]
; V2-NEXT:    str x0, [x8]
; V2-NEXT:    adrp x8, :got:g3
; V2-NEXT:    ldr x8, [x8, :got_lo12:g3]
; V2-NEXT:    str x0, [x8]
; V2-NEXT:    adrp x8, :got:g4
; V2-NEXT:    ldr x8, [x8, :got_lo12:g4]
; V2-NEXT:    str x0, [x8]
; V2-NEXT:    ret
;
; ILP32-LABEL: store4:
; ILP32:       // %bb.0:
; ILP32-NEXT:    adrp x8, :got:g1
; ILP32-NEXT:    ldr w8, [x8, :got_lo12:g1]
; ILP32-NEXT:    str x0, [x8]
; ILP32-NEXT:    adrp x8, :got:g2
; ILP32-NEXT:    ldr w8, [x8, :got_lo12:g2]
; ILP32-NEXT:    str x0, [x8]
; ILP32-NEXT:    adrp x8, :got:g3
; ILP32-NEXT:    ldr w8, [x8, :got_lo12:g3]
; ILP32-NEXT:    str x0, [x8]
; ILP32-NEXT:    adrp x8, :got:g4
; ILP32-NEXT:    ldr w8, [x8, :got_lo12:g4]
; ILP32-NEXT:    str x0, [x8]
; ILP32-NEXT:    ret
;
; A55-LABEL: store4:
; A55:       // %bb.0:
; A55-NEXT:    adrp x8, :got:g1
; A55-NEXT:    ldr x8, [x8, :got_lo12:g1]
; A55-NEXT:    adrp x9, :got:g2
; A55-NEXT:    ldr x9, [x9, :got_lo12:g2]
; A55-NEXT:    adrp x10, :got:g3
; A55-NEXT:    ldr x10, [x10, :got_lo12:g3]
; A55-NEXT:    str x0, [x8]
; A55-NEXT:    adrp x8, :got:g4
; A55-NEXT:    ldr x8, [x8, :got_lo12:g4]
; A55-NEXT:    str x0, [x9]
; A55-NEXT:    str x0, [x10]
; A55-NEXT:    str x0, [x8]
; A55-NEXT:    ret
  store i64 %x, ptr @g1
  store i64 %x, ptr @g2
  store i64 %x, ptr @g3
  store i64 %x, ptr @g4
  ret void
}

define ptr @addr2(i1 %c) {
; GENERIC-LABEL: addr2:
; GENERIC:       // %bb.0:
; GENERIC-NEXT:    adrp x8, :got:g2
; GENERIC-NEXT:    adrp x9, :got:g1
; GENERIC-NEXT:    tst w0, #0x1
; GENERIC-NEXT:    ldr x8, [x8, :got_lo12:g2]
; GENERIC-NEXT:    ldr x9, [x9, :got_lo12:g1]
; GENERIC-NEXT:    csel x0, x9, x8, ne
; GENERIC-NEXT:    ret
;
; V2-LABEL: addr2:
; V2:       // %bb.0:
; V2-NEXT:    adrp x8, :got:g2
; V2-NEXT:    adrp x9, :got:g1
; V2-NEXT:    tst w0, #0x1
; V2-NEXT:    ldr x8, [x8, :got_lo12:g2]
; V2-NEXT:    ldr x9, [x9, :got_lo12:g1]
; V2-NEXT:    csel x0, x9, x8, ne
; V2-NEXT:    ret
;
; ILP32-LABEL: addr2:
; ILP32:       // %bb.0:
; ILP32-NEXT:    adrp x8, :got:g2
; ILP32-NEXT:    adrp x9, :got:g1
; ILP32-NEXT:    tst w0, #0x1
; ILP32-NEXT:    ldr w8, [x8, :got_lo12:g2]
; ILP32-NEXT:    ldr w9, [x9, :got_lo12:g1]
; ILP32-NEXT:    csel x0, x9, x8, ne
; ILP32-NEXT:    ret
;
; A55-LABEL: addr2:
; A55:       // %bb.0:
; A55-NEXT:    adrp x8, :got:g2
; A55-NEXT:    ldr x8, [x8, :got_lo12:g2]
; A55-NEXT:    adrp x9, :got:g1
; A55-NEXT:    ldr x9, [x9, :got_lo12:g1]
; A55-NEXT:    tst w0, #0x1
; A55-NEXT:    csel x0, x9, x8, ne
; A55-NEXT:    ret
  %p = select i1 %c, ptr @g1, ptr @g2
  ret ptr %p
}

; Speculative load hardening has to see the GOT load.
define i64 @load_slh() speculative_load_hardening {
; GENERIC-LABEL: load_slh:
; GENERIC:       // %bb.0:
; GENERIC-NEXT:    adrp x8, :got:g1
; GENERIC-NEXT:    cmp sp, #0
; GENERIC-NEXT:    ldr x8, [x8, :got_lo12:g1]
; GENERIC-NEXT:    csetm x16, ne
; GENERIC-NEXT:    and x8, x8, x16
; GENERIC-NEXT:    csdb
; GENERIC-NEXT:    ldr x0, [x8]
; GENERIC-NEXT:    mov x1, sp
; GENERIC-NEXT:    and x1, x1, x16
; GENERIC-NEXT:    and x0, x0, x16
; GENERIC-NEXT:    mov sp, x1
; GENERIC-NEXT:    csdb
; GENERIC-NEXT:    ret
;
; V2-LABEL: load_slh:
; V2:       // %bb.0:
; V2-NEXT:    adrp x8, :got:g1
; V2-NEXT:    cmp sp, #0
; V2-NEXT:    ldr x8, [x8, :got_lo12:g1]
; V2-NEXT:    csetm x16, ne
; V2-NEXT:    and x8, x8, x16
; V2-NEXT:    csdb
; V2-NEXT:    ldr x0, [x8]
; V2-NEXT:    mov x1, sp
; V2-NEXT:    and x1, x1, x16
; V2-NEXT:    and x0, x0, x16
; V2-NEXT:    mov sp, x1
; V2-NEXT:    csdb
; V2-NEXT:    ret
;
; ILP32-LABEL: load_slh:
; ILP32:       // %bb.0:
; ILP32-NEXT:    adrp x8, :got:g1
; ILP32-NEXT:    cmp sp, #0
; ILP32-NEXT:    ldr w8, [x8, :got_lo12:g1]
; ILP32-NEXT:    csetm x16, ne
; ILP32-NEXT:    and w8, w8, w16
; ILP32-NEXT:    csdb
; ILP32-NEXT:    ldr x0, [x8]
; ILP32-NEXT:    mov x1, sp
; ILP32-NEXT:    and x1, x1, x16
; ILP32-NEXT:    and x0, x0, x16
; ILP32-NEXT:    mov sp, x1
; ILP32-NEXT:    csdb
; ILP32-NEXT:    ret
;
; A55-LABEL: load_slh:
; A55:       // %bb.0:
; A55-NEXT:    adrp x8, :got:g1
; A55-NEXT:    ldr x8, [x8, :got_lo12:g1]
; A55-NEXT:    cmp sp, #0
; A55-NEXT:    csetm x16, ne
; A55-NEXT:    and x8, x8, x16
; A55-NEXT:    csdb
; A55-NEXT:    ldr x0, [x8]
; A55-NEXT:    mov x1, sp
; A55-NEXT:    and x1, x1, x16
; A55-NEXT:    and x0, x0, x16
; A55-NEXT:    mov sp, x1
; A55-NEXT:    csdb
; A55-NEXT:    ret
  %1 = load i64, ptr @g1
  ret i64 %1
}

; The Cortex-A53 erratum 835769 workaround has to see the GOT loads.
define i64 @load3_a53() "target-features"="+fix-cortex-a53-835769" {
; GENERIC-LABEL: load3_a53:
; GENERIC:       // %bb.0:
; GENERIC-NEXT:    adrp x8, :got:g1
; GENERIC-NEXT:    adrp x9, :got:g2
; GENERIC-NEXT:    adrp x10, :got:g3
; GENERIC-NEXT:    ldr x8, [x8, :got_lo12:g1]
; GENERIC-NEXT:    ldr x9, [x9, :got_lo12:g2]
; GENERIC-NEXT:    ldr x8, [x8]
; GENERIC-NEXT:    ldr x9, [x9]
; GENERIC-NEXT:    ldr x10, [x10, :got_lo12:g3]
; GENERIC-NEXT:    ldr x10, [x10]
; GENERIC-NEXT:    nop
; GENERIC-NEXT:    madd x0, x8, x9, x10
; GENERIC-NEXT:    ret
;
; V2-LABEL: load3_a53:
; V2:       // %bb.0:
; V2-NEXT:    adrp x8, :got:g1
; V2-NEXT:    adrp x9, :got:g2
; V2-NEXT:    adrp x10, :got:g3
; V2-NEXT:    ldr x8, [x8, :got_lo12:g1]
; V2-NEXT:    ldr x8, [x8]
; V2-NEXT:    ldr x9, [x9, :got_lo12:g2]
; V2-NEXT:    ldr x9, [x9]
; V2-NEXT:    ldr x10, [x10, :got_lo12:g3]
; V2-NEXT:    ldr x10, [x10]
; V2-NEXT:    nop
; V2-NEXT:    madd x0, x8, x9, x10
; V2-NEXT:    ret
;
; ILP32-LABEL: load3_a53:
; ILP32:       // %bb.0:
; ILP32-NEXT:    adrp x8, :got:g1
; ILP32-NEXT:    adrp x9, :got:g2
; ILP32-NEXT:    adrp x10, :got:g3
; ILP32-NEXT:    ldr w8, [x8, :got_lo12:g1]
; ILP32-NEXT:    ldr x8, [x8]
; ILP32-NEXT:    ldr w9, [x9, :got_lo12:g2]
; ILP32-NEXT:    ldr x9, [x9]
; ILP32-NEXT:    ldr w10, [x10, :got_lo12:g3]
; ILP32-NEXT:    ldr x10, [x10]
; ILP32-NEXT:    nop
; ILP32-NEXT:    madd x0, x8, x9, x10
; ILP32-NEXT:    ret
;
; A55-LABEL: load3_a53:
; A55:       // %bb.0:
; A55-NEXT:    adrp x8, :got:g1
; A55-NEXT:    ldr x8, [x8, :got_lo12:g1]
; A55-NEXT:    adrp x9, :got:g2
; A55-NEXT:    ldr x9, [x9, :got_lo12:g2]
; A55-NEXT:    adrp x10, :got:g3
; A55-NEXT:    ldr x10, [x10, :got_lo12:g3]
; A55-NEXT:    ldr x8, [x8]
; A55-NEXT:    ldr x9, [x9]
; A55-NEXT:    ldr x10, [x10]
; A55-NEXT:    nop
; A55-NEXT:    madd x0, x8, x9, x10
; A55-NEXT:    ret
  %1 = load i64, ptr @g1
  %2 = load i64, ptr @g2
  %3 = load i64, ptr @g3
  %m = mul i64 %1, %2
  %r = add i64 %m, %3
  ret i64 %r
}
