; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -mattr=+lzcnt < %s | FileCheck %s
; i16 ctlz is promoted to the i32 form: lzcntw only writes the low 16 bits of
; its destination, leaving a merge dependency on the register's stale upper
; bits. The std::bit_width(uint16_t) shape (tcmalloc central freelist) folds
; the -16 adjustment away entirely.

define i16 @ctlz_i16(i16 %x) {
; CHECK-LABEL: ctlz_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzwl %di, %eax
; CHECK-NEXT:    lzcntl %eax, %eax
; CHECK-NEXT:    addl $-16, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %r = call i16 @llvm.ctlz.i16(i16 %x, i1 false)
  ret i16 %r
}

define i16 @ctlz_i16_zero_poison(i16 %x) {
; CHECK-LABEL: ctlz_i16_zero_poison:
; CHECK:       # %bb.0:
; CHECK-NEXT:    shll $16, %edi
; CHECK-NEXT:    lzcntl %edi, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %r = call i16 @llvm.ctlz.i16(i16 %x, i1 true)
  ret i16 %r
}

; bit_width(x) = 16 - ctlz16(x): the promoted form becomes 32 - ctlz32(zext x)
; with no partial-register write.
define i32 @bit_width_u16(ptr %p) {
; CHECK-LABEL: bit_width_u16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzwl (%rdi), %eax
; CHECK-NEXT:    lzcntl %eax, %ecx
; CHECK-NEXT:    movl $32, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    retq
  %x = load i16, ptr %p, align 2
  %ctlz = call i16 @llvm.ctlz.i16(i16 %x, i1 false)
  %z = zext i16 %ctlz to i32
  %bw = sub i32 16, %z
  ret i32 %bw
}

declare i16 @llvm.ctlz.i16(i16, i1)
